EventFileWriter:
  file_enumerator: date #or `order` which enumerates with numbers starting from 00001
  file_prefix: SlowSignalData
  folder: ~/
  ip: 127.0.0.101
  port: 5555
EventBuilder:
  SSEventBuilder:
    listen_ip: 0.0.0.0
    listen_port: 2009
    relaxed_ip_range: false
    buffer_length: 1000
    event_tw: !!float 1.e5 #nano seconds
  ZMQEventPublisher:
    ip: 127.0.0.101
    port: 5555