ssallnight:
  Daemon:
    #redirection of output (should be /dev/null when logging is fully configurable)
    stdout: '/data/astri_onsky/ssdaq_writer.log'
    stderr: '/data/astri_onsky/ssdaq_writer.log'
  Writer:
    class: ASlowSignalWriter
    file_enumerator: date #enumerates with timestamp (yr-mo-dy.H:M) or `order` which enumerates with numbers starting from 00001
    file_prefix: AllNightSlowSignalData
    folder: /data/astri_onsky/ 
    ip: 127.0.0.101
    port: 9004
    filesize_lim: 600

ssoneoff:
  Daemon:
    #redirection of output (should be /dev/null when logging is fully configurable)
    stdout: '/data/astri_onsky/ssdaq_writer.log'
    stderr: '/data/astri_onsky/ssdaq_writer.log'
  Writer:
    class: ASlowSignalWriter
    file_enumerator: date #enumerates with timestamp (yr-mo-dy.H:M) or `order` which enumerates with numbers starting from 00001
    file_prefix: SlowSignalData
    folder: /data/astri_onsky/
    ip: 127.0.0.101
    port: 9004
    filesize_lim: 600

ssrun:
  Daemon:
    #redirection of output (should be /dev/null when logging is fully configurable)
    stdout: '/data/astri_onsky/ssdaq_writer.log'
    stderr: '/data/astri_onsky/ssdaq_writer.log'
  Writer:
    class: ASlowSignalWriter
    file_enumerator: None #enumerates with timestamp (yr-mo-dy.H:M) or `order` which enumerates with numbers starting from 00001
    file_prefix: SlowSignalData
    folder: /data/astri_onsky/
    ip: 127.0.0.101
    port: 9004
    filesize_lim: 600


TriggerWriter:
  Daemon:
    #redirection of output (should be /dev/null when logging is fully configurable)
    stdout: '/data/astri_onsky/trigger_writer.log'
    stderr: '/data/astri_onsky/trigger_writer.log'
  Writer:
    class: ATriggerWriter
    file_enumerator: None #enumerates with timestamp (yr-mo-dy.H:M) or `order` which enumerates with numbers starting from 00001
    file_prefix: TriggerPackets
    folder: /data/astri_onsky/ 
    ip: 127.0.0.101
    port: 9002
    filesize_lim: 600

TimestampWriter:
  Daemon:
    #redirection of output (should be /dev/null when logging is fully configurable)
    stdout: '/data/astri_onsky/ts_writer.log'
    stderr: '/data/astri_onsky/ts_writer.log'
  Writer:
    class: ATimestampWriter
    file_enumerator: None #enumerates with timestamp (yr-mo-dy.H:M) or `order` which enumerates with numbers starting from 00001
    file_prefix: TimestampData
    folder: /tmp/
    ip: 127.0.0.101
    port: 9003
    filesize_lim: 600